extends Node

@onready var answer_label: Label = $UI_Dialog/AnswerLabel
@onready var question_label: Label = $UI_Dialog/QuestionLabel

# Background
@onready var background_image: TextureRect = $UI_Dialog/BackgroundImage
@onready var dialog_bg_image := preload("res://assets/sprites/backgrounds/background_level2_dialog.png")
@onready var main_bg_image := preload("res://assets/sprites/backgrounds/background.png")


# Entity nodes
@onready var entity_sprite: AnimatedSprite2D = $UI_Dialog/EntitySprite
@onready var title_entity_label: Label = $UI_Dialog/TitleEntityLabel
# Boss entity
@onready var boss_entity: EntityType = $BossEntity

# Buttons
@onready var ok_boss_button: TextureButton = $UI_Dialog/OkBossButton


@onready var main_level = $UI_Images

# Flow control
var is_entity_visible := false
# Text animation speed
var text_update_speed := 2.0

var level_2_transition_dialogue = [
	"You’ll now access files and images generated by AI.",
	"Your mission is clear: determine what’s real and what’s been manipulated.",
	"Use your judgment — what you see may not be what it seems.",
	"Blind trust can be the greatest lie.",
	"Level 2 begins now."
]

func _ready() -> void:
	boss_entity.text = level_2_transition_dialogue
	answer_label.visible_ratio = 0.0
	question_label.visible_ratio = 0.0
	show_tutorial()
	
func _process(_delta: float) -> void:
	if boss_entity.over:
		return
	else:
		if question_label.visible_ratio < 1.0:
			question_label.visible_ratio += \
			1.0/question_label.text.length()/text_update_speed
		elif answer_label.visible_ratio < 1.0:
			answer_label.visible_ratio += \
			1.0/answer_label.text.length()/text_update_speed


func _on_ok_boss_button_pressed() -> void:
	base_button_logic();
	boss_entity.is_it_over(answer_label);
	if boss_entity.over:
		advance_level()
		
func base_button_logic() -> void:
	answer_label.visible_ratio = 0.0
	question_label.visible_ratio = 0.0
	

func advance_level() -> void:
	main_level.visible = true;
	
func show_tutorial() -> void:
	setup_entity(boss_entity)
	
func setup_entity(entity_data: EntityType) -> void:
	# Display entity data
	entity_sprite.sprite_frames = entity_data.get_child(0).sprite_frames
	entity_sprite.play("default")
	print(entity_data.answer_text);
	answer_label.text = entity_data.answer_text
	question_label.text = entity_data.question_text
	title_entity_label.text = entity_data.entity_name
	# Mark entity visible to prevent changing displayed data
	is_entity_visible = true
